# default config
app:
  name: ^project.name^
  artifactid: ^project.artifactId^
  version: ^project.version^
  timestamp: ^timestamp^

server:
  port: 8080
  servlet.context-path: /db-mysql

spring:

  application:
    name: db-mysql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.hbm2ddl.auto: none # create-drop -- first launch | test only
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

      ddl-auto: validate
    show-sql: false

  session:
    store-type: none

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: false
      data-source-j-n-d-i: jdbc/db_mysql
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
